- name: Play level vars
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: #Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Vars from files
  hosts: localhost
  vars_files:
    - demo-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Vars from tasks
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com

- name: Facts
  hosts: localhost
  tasks:
    - name: Print Hostname
      ansible.builtin.debug:
        msg: Host Name = {{ ansible_hostname }}, {{ ansible_memfree_mb.real.free }}

#          # if any value starts with a variable then we need to quote it, Either single or double