- name: Play level vars
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: #Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}

- name: Vars from files
  hosts: localhost
  vars_files:
    - demo-vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}



- name: Vars from tasks
  hosts: localhost
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{ URL }}
      vars:
        URL: tasks.example.com


#- name: Vars from Inventory
#  hosts: localhost
#  vars:
#    URL: "This Defined By sudheer"
#  tasks:
#    - name: Print URL
#      ansible.builtin.debug:
#        msg: URL = {{ URL }}
#          # if any value starts with a variable then we need to quote it, Either single or double